import { create } from "xmlbuilder2";
import { XMLNotaFiscalDTO } from "../dtos/XmlNotasFiscalDTos";

export function toNotaFiscalXML(_data: XMLNotaFiscalDTO): string{
  
  const xml :any = create({ version: "1.0", encoding: "UTF-8" })
    .ele("EnviarLoteRpsEnvio", {
      xmlns: "http://www.abrasf.org.br/nfse.xsd",
      "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
      "xsi:schemaLocation": "nfse.xsd",
    })
      .ele("LoteRps", { versao: "2.03" })
        .ele("NumeroLote")
          .txt("00000000000")
        .up()
        .ele("CpfCnpj")
          .ele("Cnpj")
            .txt("11111111111111")
          .up()
        .up()
        .ele("QuantidadeRps")
          .txt("2")
        .up()
        .ele("ListaRps")
          // RPS 1
          .ele("Rps")
            .ele("InfDeclaracaoPrestacaoServico")
              .ele("Rps")
                .ele("IdentificacaoRps")
                  .ele("Numero").txt("0000057").up()
                  .ele("Serie").txt("U").up()
                  .ele("Tipo").txt("1").up()
                .up()
                .ele("DataEmissao").txt("2013-07-25").up()
                .ele("Status").txt("1").up()
              .up()
              .ele("Competencia").txt("2013-07-25").up()
              .ele("Servico")
                .ele("Valores")
                  .ele("ValorServicos").txt("1").up()
                  .ele("ValorDeducoes").txt("0.05").up()
                  .ele("ValorPis").txt("1").up()
                  .ele("ValorCofins").txt("2").up()
                  .ele("ValorInss").txt("3").up()
                  .ele("ValorIr").txt("4").up()
                  .ele("ValorCsll").txt("5").up()
                  .ele("OutrasRetencoes").txt("6").up()
                  .ele("ValTotTributos").txt("7").up()
                  .ele("ValorIss").txt("1").up()
                  .ele("Aliquota").txt("1").up()
                  .ele("PercentualReducaoIBS").txt("0.00").up()
                  .ele("PercentualReducaoCBS").txt("0.00").up()
                  .ele("AliquotaIBS").txt("0.10").up()
                  .ele("AliquotaCBS").txt("0.90").up()
                  .ele("ValorIBS").txt("1.00").up()
                  .ele("ValorCBS").txt("9.00").up()
                .up()
                .ele("IssRetido").txt("1").up()
                .ele("ItemListaServico").txt("07.02").up()
                .ele("CodigoCnae").txt("6422222").up()
                .ele("Discriminacao").txt("Um servico qualquer").up()
                .ele("CodigoMunicipio").txt("2507507").up()
                .ele("ExigibilidadeISS").txt("1").up()
                .ele("MunicipioIncidencia").txt("2507507").up()
                .ele("CodigoTributacaoNacional").txt("010101").up()
                .ele("CodigoNBS").txt("1.1502.10.00").up()
                .ele("CodigoClassificacaoTributaria").txt("000001").up()
                .ele("CodigoIndicadorOperacaoFornecimento").txt("100301").up()
              .up()
              .ele("Prestador")
                .ele("CpfCnpj")
                  .ele("Cpf").txt("11111111111").up()
                .up()
              .up()
              .ele("Tomador")
                .ele("InformaTomador").txt("1").up()
                .ele("IdentificacaoTomador")
                  .ele("CpfCnpj")
                    .ele("Cnpj").txt("12345678901234").up()
                  .up()
                .up()
                .ele("RazaoSocial").txt("RAZAO SOCIAL FUNÇÃO TESTE 1").up()
                .ele("Endereco")
                  .ele("Endereco").txt("RUA X ÓTIMA").up()
                  .ele("Numero").txt("2018").up()
                  .ele("Complemento").txt("COMPLEMENTO AÇUCAR").up()
                  .ele("Bairro").txt("BAIRRO A").up()
                  .ele("CodigoMunicipio").txt("2700805").up()
                  .ele("Uf").txt("AL").up()
                  .ele("Cep").txt("57000000").up()
                .up()
                .ele("Contato")
                  .ele("Telefone").txt("wewewew").up()
                  .ele("Email").txt("teste").up()
                .up()
              .up()
              .ele("Intermediario")
                .ele("InformaIntermediario").txt("0").up()
                .ele("IdentificacaoIntermediario")
                  .ele("CpfCnpj")
                    .ele("Cnpj").txt("12345678901234").up()
                  .up()
                .up()
                .ele("RazaoSocial").txt("RAZAO SOCIAL FUNÇÃO TESTE 1").up()
                .ele("Endereco")
                  .ele("Endereco").txt("RUA X ÓTIMA").up()
                  .ele("Numero").txt("2018").up()
                  .ele("Complemento").txt("COMPLEMENTO AÇUCAR").up()
                  .ele("Bairro").txt("BAIRRO A").up()
                  .ele("CodigoMunicipio").txt("2700805").up()
                  .ele("Uf").txt("AL").up()
                  .ele("Cep").txt("57000000").up()
                .up()
                .ele("Contato")
                  .ele("Telefone").txt("wewewew").up()
                  .ele("Email").txt("teste").up()
                .up()
              .up()
              .ele("Destinatario")
                .ele("DestinatarioTomador").txt("0").up()
                .ele("IdentificacaoDestinatario")
                  .ele("CpfCnpj")
                    .ele("Cnpj").txt("12345678901234").up()
                  .up()
                .up()
                .ele("RazaoSocial").txt("RAZAO SOCIAL FUNÇÃO TESTE 1").up()
                .ele("Endereco")
                  .ele("Endereco").txt("RUA X ÓTIMA").up()
                  .ele("Numero").txt("2018").up()
                  .ele("Complemento").txt("COMPLEMENTO AÇUCAR").up()
                  .ele("Bairro").txt("BAIRRO A").up()
                  .ele("CodigoMunicipio").txt("2700805").up()
                  .ele("Uf").txt("AL").up()
                  .ele("Cep").txt("57000000").up()
                .up()
                .ele("Contato")
                  .ele("Telefone").txt("wewewew").up()
                  .ele("Email").txt("teste").up()
                .up()
              .up()
              .ele("RegimeEspecialTributacao").txt("1").up()
              .ele("OptanteSimplesNacional").txt("1").up()
              .ele("IncentivoFiscal").txt("1").up()
              .ele("UsoConsumoPessoal").txt("0").up()
              .ele("TipoEnteGovernamental").txt("4").up()
              .ele("ServicoResultadoOutroPais").txt("1").up()
              .ele("PaisPrestacao").txt("US").up()
              .ele("ModoPrestacao").txt("2").up()
              .ele("VinculoPartes").txt("0").up()
              .ele("TipoMoeda").txt("USD").up()
              .ele("ValorMoedaEstrangeira").txt("25.00").up()
              .ele("FomentoPrestador").txt("02").up()
              .ele("FomentoTomador").txt("24").up()
              .ele("VinculoMovimentacaoBens").txt("0").up()
              .ele("NumeroDI").txt("123456789").up()
              .ele("NumeroRE").txt("987654321").up()
              .ele("EnviarMDIC").txt("1").up()
              .ele("InformacoesImovel")
                .ele("InscricaoImobiliaria").txt("123456789").up()
                .ele("IdentificacaoImovelCib").txt("12345678").up()
                .ele("EnderecoImovel")
                  .ele("Cep").txt("57000000").up()
                  .ele("EnderecoExterior")
                    .ele("CodigoPostal").txt("12345-678").up()
                    .ele("CidadeExterior").txt("Lisboa").up()
                    .ele("EstadoProvinciaRegiao").txt("Lisboa").up()
                  .up()
                  .ele("Logradouro").txt("Rua das Flores").up()
                  .ele("Numero").txt("100").up()
                  .ele("Complemento").txt("Apto 202").up()
                  .ele("Bairro").txt("Centro").up()
                .up()
              .up()
              .ele("InformacoesObra")
                .ele("InscricaoImobiliaria").txt("123456789").up()
                .ele("IdentificacaoObraCnoCei").txt("123456789012").up()
                .ele("EnderecoObra")
                  .ele("Cep").txt("57000000").up()
                  .ele("EnderecoExterior")
                    .ele("CodigoPostal").txt("12345-678").up()
                    .ele("CidadeExterior").txt("Lisboa").up()
                    .ele("EstadoProvinciaRegiao").txt("Lisboa").up()
                  .up()
                  .ele("Logradouro").txt("Rua das Flores").up()
                  .ele("Numero").txt("100").up()
                  .ele("Complemento").txt("Apto 202").up()
                  .ele("Bairro").txt("Centro").up()
                .up()
              .up()
              .ele("InformacoesEvento")
                .ele("Nome").txt("Teste").up()
                .ele("IdentificacaoEvento").txt("123456789012").up()
                .ele("DataInicialEvento").txt("2026-01-01").up()
                .ele("DataFinalEvento").txt("2026-01-15").up()
                .ele("EnderecoEvento")
                  .ele("Cep").txt("57000000").up()
                  .ele("EnderecoExterior")
                    .ele("CodigoPostal").txt("12345-678").up()
                    .ele("CidadeExterior").txt("Lisboa").up()
                    .ele("EstadoProvinciaRegiao").txt("Lisboa").up()
                  .up()
                  .ele("Logradouro").txt("Rua das Flores").up()
                  .ele("Numero").txt("100").up()
                  .ele("Complemento").txt("Apto 202").up()
                  .ele("Bairro").txt("Centro").up()
                .up()
              .up()
              .ele("ExploracaoRodovia")
                .ele("CategoriaVeiculo").txt("01").up()
                .ele("NumeroEixos").txt("4").up()
                .ele("TipoRodagem").txt("2").up()
                .ele("PlacaVeiculo").txt("ABC1234").up()
                .ele("OrientacaoPassagem").txt("270").up()
                .ele("CodigoAcessoConcessionaria").txt("1234567890").up()
                .ele("CodigoContratoConcessionaria").txt("0001").up()
              .up()
              .ele("InformacoesLocacao")
                .ele("CategoriaServicoLocacao").txt("1").up()
                .ele("TipoObjetoLocacao").txt("2").up()
                .ele("ExtensaoTotalLocacao").txt("23.50").up()
                .ele("NumeroTotalPostes").txt("250").up()
              .up()
            .up()
          .up()
          // RPS 2
          .ele("Rps")
            .ele("InfDeclaracaoPrestacaoServico")
              .ele("Rps")
                .ele("IdentificacaoRps")
                  .ele("Numero").txt("0000058").up()
                  .ele("Serie").txt("U").up()
                  .ele("Tipo").txt("1").up()
                .up()
                .ele("DataEmissao").txt("2013-07-25").up()
                .ele("Status").txt("1").up()
              .up()
              .ele("Competencia").txt("2013-07-25").up()
              .ele("Servico")
                .ele("Valores")
                  .ele("ValorServicos").txt("1000").up()
                  .ele("ValorDeducoes").txt("500").up()
                  .ele("ValorPis").txt("10").up()
                  .ele("ValorCofins").txt("20").up()
                  .ele("ValorInss").txt("30").up()
                  .ele("ValorIr").txt("40").up()
                  .ele("ValorCsll").txt("50").up()
                  .ele("OutrasRetencoes").txt("60").up()
                  .ele("ValTotTributos").txt("70").up()
                  .ele("ValorIss").txt("1.50").up()
                  .ele("Aliquota").txt("1.00").up()
                  .ele("PercentualReducaoIBS").txt("0.00").up()
                  .ele("PercentualReducaoCBS").txt("0.00").up()
                  .ele("AliquotaIBS").txt("0.10").up()
                  .ele("AliquotaCBS").txt("0.90").up()
                  .ele("ValorIBS").txt("1.00").up()
                  .ele("ValorCBS").txt("9.00").up()
                .up()
                .ele("IssRetido").txt("2").up()
                .ele("ItemListaServico").txt("01.01").up()
                .ele("CodigoCnae").txt("6411111").up()
                .ele("Discriminacao").txt("Um servico qualquer").up()
                .ele("CodigoMunicipio").txt("2507507").up()
                .ele("ExigibilidadeISS").txt("1").up()
                .ele("MunicipioIncidencia").txt("2507507").up()
                .ele("CodigoTributacaoNacional").txt("010101").up()
                .ele("CodigoNBS").txt("1.1502.10.00").up()
                .ele("CodigoClassificacaoTributaria").txt("000001").up()
                .ele("CodigoIndicadorOperacaoFornecimento").txt("100301").up()
              .up()
              .ele("Prestador")
                .ele("CpfCnpj")
                  .ele("Cpf").txt("11111111111").up()
                .up()
              .up()
              .ele("Tomador")
                .ele("InformaTomador").txt("1").up()
                .ele("IdentificacaoTomador")
                  .ele("CpfCnpj")
                    .ele("Cpf").txt("99999999999").up()
                  .up()
                .up()
                .ele("RazaoSocial").txt("RAZAO SOCIAL FUNÇÃO TESTE 1").up()
                .ele("Endereco")
                  .ele("Endereco").txt("RUA X").up()
                  .ele("Numero").txt("2018").up()
                  .ele("Complemento").txt("COMPLEMENTO").up()
                  .ele("Bairro").txt("BAIRRO A").up()
                  .ele("CodigoMunicipio").txt("2700805").up()
                  .ele("Uf").txt("AL").up()
                  .ele("Cep").txt("57000000").up()
                .up()
                .ele("Contato")
                  .ele("Telefone").txt("wewewew").up()
                  .ele("Email").txt("teste").up()
                .up()
              .up()
              .ele("Intermediario")
                .ele("InformaIntermediario").txt("0").up()
                .ele("IdentificacaoIntermediario")
                  .ele("CpfCnpj")
                    .ele("Cpf").txt("99999999999").up()
                  .up()
                .up()
                .ele("RazaoSocial").txt("RAZAO SOCIAL FUNÇÃO TESTE 1").up()
                .ele("Endereco")
                  .ele("Endereco").txt("RUA X").up()
                  .ele("Numero").txt("2018").up()
                  .ele("Complemento").txt("COMPLEMENTO").up()
                  .ele("Bairro").txt("BAIRRO A").up()
                  .ele("CodigoMunicipio").txt("2700805").up()
                  .ele("Uf").txt("AL").up()
                  .ele("Cep").txt("57000000").up()
                .up()
                .ele("Contato")
                  .ele("Telefone").txt("wewewew").up()
                  .ele("Email").txt("teste").up()
                .up()
              .up()
              .ele("Destinatario")
                .ele("DestinatarioTomador").txt("0").up()
                .ele("IdentificacaoDestinatario")
                  .ele("CpfCnpj")
                    .ele("Cpf").txt("99999999999").up()
                  .up()
                .up()
                .ele("RazaoSocial").txt("RAZAO SOCIAL FUNÇÃO TESTE 1").up()
                .ele("Endereco")
                  .ele("Endereco").txt("RUA X").up()
                  .ele("Numero").txt("2018").up()
                  .ele("Complemento").txt("COMPLEMENTO").up()
                  .ele("Bairro").txt("BAIRRO A").up()
                  .ele("CodigoMunicipio").txt("2700805").up()
                  .ele("Uf").txt("AL").up()
                  .ele("Cep").txt("57000000").up()
                .up()
                .ele("Contato")
                  .ele("Telefone").txt("wewewew").up()
                  .ele("Email").txt("teste").up()
                .up()
              .up()
              .ele("RegimeEspecialTributacao").txt("1").up()
              .ele("OptanteSimplesNacional").txt("2").up()
              .ele("IncentivoFiscal").txt("1").up()
              .ele("UsoConsumoPessoal").txt("0").up()
              .ele("TipoEnteGovernamental").txt("4").up()
              .ele("ServicoResultadoOutroPais").txt("0").up()
            .up()
          .up()
        .up()
      .up()
    .up();

  return xml.end({ prettyPrint: true });
}